@startuml
left to right direction
actor "Guest" as g
actor "Candidate" as c

rectangle "Job Discovery" {
  usecase "Tìm kiếm việc làm" as UC1
  usecase "Lọc việc làm nâng cao" as UC2
  usecase "Xem chi tiết công việc" as UC3
  usecase "Xem công ty tuyển dụng" as UC4
}

g --> UC1
g --> UC3
c --> UC1
c --> UC2
UC1 <.. UC2 : <<extend>>
UC3 ..> UC4 : <<include>>
@enduml
