@startuml
left to right direction
actor "Admin" as adm
actor "Employer" as e

rectangle "Company Verification" {
  usecase "Cung cấp GPKD & Hồ sơ" as UC1
  usecase "Duyệt hồ sơ công ty" as UC2
  usecase "Kiểm tra tính pháp lý" as UC3
  usecase "Cấp mức xác thực (VerifLevel)" as UC4
  usecase "Từ chối xác thực" as UC5
}

e --> UC1
adm --> UC2
UC2 ..> UC3 : <<include>>
UC2 ..> UC4 : <<extend>>
UC2 ..> UC5 : <<extend>>
@enduml
