@startuml
actor Admin
participant FE
participant CatalogSvc
database DB


Admin -> FE : Mở Danh mục
FE -> CatalogSvc : list()
CatalogSvc -> DB : SELECT categories
DB --> CatalogSvc : rows
CatalogSvc --> FE : list
opt Thêm/Sửa/Xóa
Admin -> FE : action(payload)
FE -> CatalogSvc : upsert/delete
CatalogSvc -> DB : INSERT/UPDATE/DELETE
DB --> CatalogSvc : ok
CatalogSvc --> FE : success
end
@enduml