@startuml
left to right direction
actor "User" as u
actor "Admin" as adm

rectangle "Violation Reporting" {
  usecase "Gửi báo cáo vi phạm" as UC1
  usecase "Theo dõi trạng thái báo cáo" as UC2
  usecase "Xử lý báo cáo vi phạm" as UC3
  usecase "Thống kê báo cáo" as UC4
}

u --> UC1
u --> UC2
adm --> UC3
adm --> UC4
@enduml
