@startuml
left to right direction
actor "Candidate" as c

rectangle "Job Application" {
  usecase "Nộp đơn ứng tuyển" as UC1
  usecase "Chọn CV từ hồ sơ" as UC2
  usecase "Viết thư giới thiệu" as UC3
  usecase "Rút đơn ứng tuyển" as UC4
  usecase "Theo dõi trạng thái đơn" as UC5
}

c --> UC1
c --> UC4
c --> UC5
UC1 ..> UC2 : <<include>>
UC1 ..> UC3 : <<include>>
@enduml
