-- V1.1 Flyway Setup
-- This is a placeholder migration script to initialize Flyway for the ITing Job Portal.
-- Since spring.flyway.baseline-on-migrate=true is configured,
-- the existing database schema generated by Hibernate/data.sql will be baselined automatically.

SELECT 1;
