-- =============================================================================
-- V49 — Finalize Company decoupling from Account (Phase 2 of HR refactor)
-- =============================================================================
-- Phase 2 (breaking schema):
--   * Update legacy role 'COMPANY' → 'EMPLOYER' ở Account
--   * Drop FK fk_company_account (đã được thay thế bằng affiliation từ V48)
--   * Convert company_id thành IDENTITY (để new Company rows tự sinh id)
--   * Verify tax_code không NULL/rỗng → dedup nếu trùng → SET NOT NULL + UNIQUE
-- Java side: bỏ @MapsId Account ở Company, đổi @Id thành @GeneratedValue(IDENTITY).
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────
-- 1) Migrate legacy role 'COMPANY' → 'EMPLOYER'
-- ─────────────────────────────────────────────────────────────────
UPDATE account SET role = 'EMPLOYER' WHERE role = 'COMPANY';

-- ─────────────────────────────────────────────────────────────────
-- 2) Drop FK fk_company_account (cũ — bắt company_id phải tồn tại trong account)
--    Đồng thời drop mọi FK còn lại từ company.company_id → account(id) nếu có.
-- ─────────────────────────────────────────────────────────────────
DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN
        SELECT conname FROM pg_constraint
         WHERE conrelid = 'company'::regclass
           AND contype  = 'f'
           AND pg_get_constraintdef(oid) ILIKE '%REFERENCES account%'
           AND pg_get_constraintdef(oid) NOT ILIKE '%info_source_affiliation_id%'
    LOOP
        EXECUTE format('ALTER TABLE company DROP CONSTRAINT %I', r.conname);
    END LOOP;
END$$;

-- ─────────────────────────────────────────────────────────────────
-- 3) Convert company.company_id sang IDENTITY (auto-generated).
--    Existing rows giữ nguyên id (đã match account.id từ schema cũ).
--    New rows từ Phase 3 onwards sẽ tự sinh id từ IDENTITY (start sau max hiện tại).
-- ─────────────────────────────────────────────────────────────────
DO $$
DECLARE max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(company_id), 0) INTO max_id FROM company;
    -- Nếu cột chưa có IDENTITY, thêm vào
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = current_schema()
           AND table_name = 'company'
           AND column_name = 'company_id'
           AND is_identity = 'YES'
    ) THEN
        EXECUTE format(
            'ALTER TABLE company ALTER COLUMN company_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
            max_id + 1
        );
    END IF;
END$$;

-- ─────────────────────────────────────────────────────────────────
-- 4) Auto-fix company có tax_code NULL / rỗng
--    Sinh placeholder 'AUTO-{company_id}' để migration không bị block.
-- ─────────────────────────────────────────────────────────────────
DO $$
DECLARE bad_count INT; r RECORD;
BEGIN
    SELECT COUNT(*) INTO bad_count
      FROM company
     WHERE tax_code IS NULL OR TRIM(tax_code) = '';

    IF bad_count > 0 THEN
        RAISE NOTICE 'V49: Tìm thấy % company có tax_code NULL/rỗng → auto-fill placeholder.', bad_count;

        FOR r IN
            SELECT company_id FROM company
             WHERE tax_code IS NULL OR TRIM(tax_code) = ''
        LOOP
            UPDATE company
               SET tax_code = 'AUTO-' || r.company_id
             WHERE company_id = r.company_id;
            RAISE NOTICE '  → company_id=% set tax_code=AUTO-%', r.company_id, r.company_id;
        END LOOP;
    END IF;
END$$;

-- ─────────────────────────────────────────────────────────────────
-- 5) Dedup tax_code — chuyển FK con sang canonical (id nhỏ nhất), xoá duplicate.
--    Bao gồm: job, company_hr_affiliations, company_audit_log, company_kyb_notes,
--             company_reviews, user_follow_company, company_industries,
--             company_tech_stack, company_benefits.
-- ─────────────────────────────────────────────────────────────────
DO $$
DECLARE r RECORD; canonical_id BIGINT;
BEGIN
    FOR r IN
        SELECT tax_code, MIN(company_id) AS canon_id, array_agg(company_id ORDER BY company_id) AS all_ids
          FROM company
         GROUP BY tax_code
        HAVING COUNT(*) > 1
    LOOP
        canonical_id := r.canon_id;
        RAISE NOTICE 'Dedup tax_code=% canonical=% all=%', r.tax_code, canonical_id, r.all_ids;

        UPDATE job                       SET company_id = canonical_id WHERE company_id = ANY(r.all_ids) AND company_id <> canonical_id;
        UPDATE company_hr_affiliations   SET company_id = canonical_id WHERE company_id = ANY(r.all_ids) AND company_id <> canonical_id;
        UPDATE company_audit_log         SET company_id = canonical_id WHERE company_id = ANY(r.all_ids) AND company_id <> canonical_id;

        -- Bảng phụ company_kyb_notes / company_reviews / user_follow_company / collection tables
        -- (skip nếu bảng không tồn tại)
        BEGIN
            EXECUTE 'UPDATE company_kyb_notes SET company_id = $1 WHERE company_id = ANY($2) AND company_id <> $1'
                USING canonical_id, r.all_ids;
        EXCEPTION WHEN undefined_table THEN NULL; END;

        BEGIN
            EXECUTE 'UPDATE company_reviews SET company_id = $1 WHERE company_id = ANY($2) AND company_id <> $1'
                USING canonical_id, r.all_ids;
        EXCEPTION WHEN undefined_table THEN NULL; END;

        BEGIN
            EXECUTE 'UPDATE user_follow_company SET company_id = $1 WHERE company_id = ANY($2) AND company_id <> $1'
                USING canonical_id, r.all_ids;
        EXCEPTION WHEN undefined_table THEN NULL; END;

        BEGIN
            EXECUTE 'DELETE FROM company_industries WHERE company_id = ANY($1) AND company_id <> $2'
                USING r.all_ids, canonical_id;
        EXCEPTION WHEN undefined_table THEN NULL; END;

        BEGIN
            EXECUTE 'DELETE FROM company_tech_stack WHERE company_id = ANY($1) AND company_id <> $2'
                USING r.all_ids, canonical_id;
        EXCEPTION WHEN undefined_table THEN NULL; END;

        BEGIN
            EXECUTE 'DELETE FROM company_benefits WHERE company_id = ANY($1) AND company_id <> $2'
                USING r.all_ids, canonical_id;
        EXCEPTION WHEN undefined_table THEN NULL; END;

        DELETE FROM company WHERE company_id = ANY(r.all_ids) AND company_id <> canonical_id;
    END LOOP;
END$$;

-- ─────────────────────────────────────────────────────────────────
-- 6) tax_code NOT NULL + UNIQUE
-- ─────────────────────────────────────────────────────────────────
ALTER TABLE company ALTER COLUMN tax_code SET NOT NULL;
ALTER TABLE company ADD CONSTRAINT uniq_company_taxcode UNIQUE (tax_code);
