@startuml
actor Candidate
participant FE
participant NotifSvc
database DB


Candidate -> FE : Click biểu tượng chuông
FE -> NotifSvc : list(userId,page) ' sync
NotifSvc -> DB : SELECT notifications DESC ' sync
DB --> NotifSvc : rows
NotifSvc --> FE : list ' reply
@enduml