@startuml
actor Candidate
participant FE
participant ReportSvc
participant NotifSvc
database DB


Candidate -> FE : Báo cáo vi phạm
FE -> ReportSvc : createReport(userId,target,reason,evidence) ' sync
ReportSvc -> DB : INSERT report(status="open") ' sync
DB --> ReportSvc : ok
ReportSvc ->> NotifSvc : notify(Admin, reportId) ' ASYNC
ReportSvc --> FE : success + trackingId ' reply
@enduml