@startuml
left to right direction
skinparam packageStyle rectangle

actor "Guest" as g
actor "User" as u

rectangle "Authentication System" {
  usecase "Đăng ký tài khoản" as UC1
  usecase "Xác thực OTP qua Email" as UC2
  usecase "Đăng nhập" as UC3
  usecase "Quên mật khẩu" as UC4
  usecase "Đăng nhập bằng Google" as UC5
}

g --> UC1
g --> UC3
g --> UC5
UC1 ..> UC2 : <<include>>
u --> UC4
@enduml
