@startuml
left to right direction
actor "Employer (HR)" as hr

rectangle "Applicant Management" {
  usecase "Xem danh sách hồ sơ" as UC1
  usecase "Xem chi tiết bộ hồ sơ" as UC2
  usecase "Tải hồ sơ CV" as UC3
  usecase "Chấp nhận hồ sơ" as UC4
  usecase "Từ chối hồ sơ" as UC5
  usecase "Tìm kiếm ứng viên bằng AI/OCR" as UC6
}

hr --> UC1
hr --> UC2
hr --> UC6
UC2 ..> UC3 : <<extend>>
UC2 ..> UC4 : <<extend>>
UC2 ..> UC5 : <<extend>>
@enduml
