@startuml
actor Admin
participant FE
participant ReportSvc
database DB


Admin -> FE : Chọn bộ lọc thống kê
FE -> ReportSvc : runStats(filters) ' sync
ReportSvc -> DB : aggregate by dim/time ' sync
DB --> ReportSvc : results
ReportSvc --> FE : charts/tables ' reply
opt Export file
FE -> ReportSvc : export(type=PDF/XLSX) ' sync
ReportSvc ->> ReportSvc : renderExportJob() ' SELF + ASYNC (nếu lớn)
ReportSvc --> FE : file link / job id ' reply
end
@enduml