spring.application.name=ITing



# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://pg-390391d1-nghiavo6777-55a3.g.aivencloud.com:23388/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_3BmfcTu4X9KJ9JrBzLV

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.driver-class-name=org.postgresql.Driver
