spring.application.name=ITing



# ===============================
# DATABASE CONFIGURATION
# ===============================
 spring.datasource.url=jdbc:postgresql://pg-390391d1-nghiavo6777-55a3.g.aivencloud.com:23388/defaultdb?sslmode=require
 spring.datasource.username=avnadmin
 spring.datasource.password=AVNS_3BmfcTu4X9KJ9JrBzLV

# ===============================
# JPA / HIBERNATE
# ===============================
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
 spring.datasource.driver-class-name=org.postgresql.Driver
# jwt.secret=supersecretkeysupersecretkey123
# jwt.expiration=86400000



# ===============================
# APP CONFIGURATION
# ===============================
spring.application.name=iting-job-portal
server.port=8080


# ===============================
# JPA / HIBERNATE
# ===============================
# create-drop: Tạo lại bảng mỗi khi chạy lại app (Dữ liệu cũ sẽ mất)
# update: Giữ lại dữ liệu cũ
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Quan trọng: Đợi Hibernate tạo bảng xong mới chạy file data.sql
spring.jpa.defer-datasource-initialization=true

# ===============================
# DATA INITIALIZATION (RBAC)
# ===============================
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:rbc-init.sql
spring.sql.init.encoding=UTF-8

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# ===============================
# JWT CONFIGURATION (Custom)
# ===============================
# Secret key 256-bit
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 24 giờ (tính bằng milliseconds)
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
