@startuml
left to right direction
actor "User" as u

rectangle "User Interaction" {
  usecase "Chat thời gian thực" as UC1
  usecase "Nhận thông báo hệ thống" as UC2
  usecase "Theo dõi Công ty" as UC3
  usecase "Bật/Tắt thông báo" as UC4
}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
@enduml
