@startuml
left to right direction
actor "Employer (HR)" as hr

rectangle "Job Management" {
  usecase "Đăng tin tuyển dụng" as UC1
  usecase "Gửi tin để Admin duyệt" as UC2
  usecase "Cập nhật tin đã đăng" as UC3
  usecase "Gia hạn thời gian tuyển" as UC4
  usecase "Đóng/Mở lại tin" as UC5
  usecase "Xóa tin tuyển dụng" as UC6
}

hr --> UC1
hr --> UC2
hr --> UC3
hr --> UC4
hr --> UC5
hr --> UC6
@enduml
